{% set package_name = "atef" %}
{% set version = "1.4.0" %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/atef/archive/v{{ version }}.tar.gz
  sha256: c3eee871564684008ab4f8037c80b00095a2460b665cba37c841546e56221519

build:
  entry_points:
    - atef = atef.bin.main:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.7
  - pip
  - setuptools_scm
  run:
  - python >=3.7
  - apischema
  - archapp >=1.1.0
  - bluesky
  - bluesky-queueserver >=0.0.19
  - bluesky-widgets
  - databroker <2.0.0a0
  - happi
  - ipython
  - numpy
  - ophyd
  - pcdsutils >=0.14.1
  - pydm
  - pyyaml
  - qtpy
  - pyqt
  - reportlab
  - rich
  - typhos
  - typing-extensions



test:
  imports:
  - atef
  requires:
  - coverage
  - doctr
  - docs-versions-menu
  - numpydoc
  - flake8
  - pytest
  - pytest-timeout
  - pytest-asyncio
  - pytest-qt
  - pcdsdevices >=7.1.0
  - sphinx
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinxcontrib-jquery



about:
  dev_url: https://github.com/pcdshub/atef
  doc_url: https://pcdshub.github.io/atef/
  home: https://github.com/pcdshub/atef
  license: LicenseRef-BSD-3-Clause-SLAC
  license_file: LICENSE
  summary: Python Automated Test Execution Framework



extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
